### ISSUE TITLE
关于example_train_ImagingBased.py的问题

### ISSUE THREAD

**Issue by yuzheleilei** [Roshan1992/RedeHist#2]
你好，当我按照README文档运行的时候，执行到以下命令时报错
``` python
    python -u example_train_ImagingBased.py
```
发现import  pytorch_lightning 出现问题，ModuleNotFoundError: No module named 'pytorch_lightning'
无论是重装，还是降低版本，都无法解决这个问题
conda环境与environment.yml所描述的一样，我未作任何额外的修改
``` shell
conda list
# packages in environment at /cluster/facility/hlhuang/miniconda3/envs/RedeHist_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohappyeyeballs          2.4.0                    pypi_0    pypi
aiohttp                   3.10.5                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anndata                   0.10.5.post1             pypi_0    pypi
array-api-compat          1.8                      pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cellpose                  2.2.3                    pypi_0    pypi
certifi                   2024.7.4                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
fastremap                 1.15.0                   pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
idna                      3.7                      pypi_0    pypi
imagecodecs               2024.6.1                 pypi_0    pypi
importlib-resources       6.4.3                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
lightning-utilities       0.11.6                   pypi_0    pypi
llvmlite                  0.39.1                   pypi_0    pypi
matplotlib                3.7.5                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
ncurses                   6.5                  h59595ed_0    conda-forge
networkx                  3.2.1                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.20.3                   pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openssl                   3.3.1                h4bc722e_2    conda-forge
packaging                 24.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
patsy                     0.5.6                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pynndescent               0.5.13                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.9.18          h0755675_1_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch-lightning         1.9.5                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
redehist                  1.0.0                    pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
roifile                   2024.5.24                pypi_0    pypi
scanpy                    1.9.3                    pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scikit-misc               0.1.4                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
session-info              1.0.0                    pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                72.1.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
statsmodels               0.14.1                   pypi_0    pypi
stdlib-list               0.10.0                   pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.8.10                pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
torch                     1.12.1+cpu               pypi_0    pypi
torchaudio                0.12.1+cpu               pypi_0    pypi
torchmetrics              1.4.1                    pypi_0    pypi
torchvision               0.13.1+cpu               pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
triton                    3.0.0                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
umap-learn                0.5.6                    pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.20.0                   pypi_0    pypi
```

**Comment by yuzheleilei** [comment]
昨天是liunx服务器，今天在本地的windows系统下测试RedeHist时，发现出问题的是， **AttributeError: module 'numpy.typing' has no attribute 'NDArray'** 。
通过升级numpy到1.21.0版本，我修复了bug，脚本可以运行。
因此我又重装了环境,发现了一样的bug
```
python -u example_train_ImagingBased.py
Traceback (most recent call last):
  File "/cluster/facility/hlhuang/zhangl/ZL003_spatial_analysis/RedeHist/example_train_ImagingBased.py", line 12, in <module>
    import pytorch_lightning as pl
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/pytorch_lightning/utilities/__init__.py", line 23, in <module>
    from pytorch_lightning.utilities.imports import (  # noqa: F401
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/pytorch_lightning/utilities/imports.py", line 28, in <module>
    _TORCHMETRICS_GREATER_EQUAL_0_11 = compare_version("torchmetrics", operator.ge, "0.11.0")  # using new API with task
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/lightning_utilities/core/imports.py", line 78, in compare_version
    pkg = importlib.import_module(package)
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/torchmetrics/__init__.py", line 23, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/torchmetrics/metric.py", line 42, in <module>
    from torchmetrics.utilities.plot import _AX_TYPE, _PLOT_OUT_TYPE, plot_single_or_multi_val
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/torchmetrics/utilities/plot.py", line 25, in <module>
    import matplotlib
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/matplotlib/__init__.py", line 129, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/matplotlib/colors.py", line 51, in <module>
    from PIL import Image
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/PIL/Image.py", line 68, in <module>
    from ._typing import StrOrBytesPath, TypeGuard
  File "/cluster/facility/hlhuang/miniconda3/envs/RedeHist_env/lib/python3.9/site-packages/PIL/_typing.py", line 10, in <module>
    NumpyArray = npt.NDArray[Any]
AttributeError: module 'numpy.typing' has no attribute 'NDArray'
```
```
pip install numpy==1.21.0
Collecting numpy==1.21.0
  Downloading numpy-1.21.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 572 kB/s
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
Successfully installed numpy-1.21.0
```
进行同样的升级操作后，脚本似乎可以正常运行了

**Comment by yuzheleilei** [comment]
建议作者进行进一步测试
